### ISSUE TITLE
quality lower 84

### ISSUE THREAD

**Issue by themaikmueller** [doterax/guetzli-cuda-win-binaries#1]
Could you disable the hardcoded minimum quality level of 84, please? I did tests with lower values in the original version, and there might be scenarios where lower values are useful.

**Comment by doterax** [comment]
Shure. I will make it tonight or tomorrow.

**Comment by themaikmueller** [comment]
Cool, thank you very much! 👍🏻

**Comment by doterax** [comment]
I have just thinked that I need to close this repo, and continue making releases in forked repo

https://github.com/doterax/guetzli-cuda-opencl

Would you open (copy and paste :) ) this issue in that repository.

Thank you.

**Comment by doterax** [comment]
Fixed. You can find release here https://github.com/doterax/guetzli-cuda-opencl
