### ISSUE TITLE
very high-resolution files

### ISSUE THREAD

**Issue by themaikmueller** [doterax/guetzli-cuda-win-binaries#2]
I recognized this in the official version a long time ago too, but since you're probably the only one who is currently working on this code and it never made much sense to fix this in the CPU-version (encoding such pics takes ages with that), I'll bring it up here. 

There is an internal limitation that makes guetzli crash with very high-resolution files. I do not know where exactly that limit is, but narrowed it down to 4040 x 3030 being processed and 4050 x 3038 not being processed.

Happens with the original version too (i just can go drink a coffee when I start this) and shouldn't be an issue of available RAM or GPU-RAM.

**Comment by doterax** [comment]
I have just thinked that I need to close this repo, and continue making releases in forked repo

https://github.com/doterax/guetzli-cuda-opencl

Would you open (copy and paste :) ) this issue in that repository.

Thank you.

**Comment by themaikmueller** [comment]
I will, but right now there is no issues section on that one. ;)

**Comment by doterax** [comment]
I have tested guetzli CUDA with three big files. And I have only 6 GB of GPU RAM.

Also I have added `--nomemlimit` switch to disable memory limitation check.

|Size|Time to compress|
| :- | :- | 
|5000x5000|128.78 sec|
|7000x7000|222.16 sec|
|10000x10000|Maxed out GPU RAM|

If you continue experiencing this problems open ticket with file that not works for you.
